//用于全局字体，样式，navbar，footer等
import type { Metadata } from "next";

//引入google字体
import { Inter } from "next/font/google";
import "./globals.css";

//引入clerk
import { ClerkProvider } from "@clerk/nextjs";

//生成一个叫inter的实例，它使用google字体Inter的子集latin
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 将所有内容包在provider里
      //afterSignOutUrl="/": always come back root page,and this is default
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        {/* 给全局的body加了一个classname，其中里面是字体inter以及它的classname */}
        <body
          className={inter.className}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>

  );
}
